# Generated by Django 3.0.1 on 2020-04-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio_proj',
            new_name='portfolio',
        ),
    ]
