# Generated by Django 3.0.1 on 2020-04-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200419_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='portfolio_model',
        ),
    ]
